[package]
name = "pusu"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
broker_macro = { path = "broker_macro" }
consumer_macro = { path = "consumer_macro" }
producer_macro = { path = "producer_macro" }
serde = { version = "1.0", features = ["derive"] }
#postcard = "1.1.3"
postcard = {"version" = "1.1.3", features = ["use-std"]}

[features]
default = ["broker", "consumer", "producer"]
broker = []
consumer = []
producer = []
