[package]
name = "pusu"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
broker_macro = { path = "broker_macro" }
consumer_macro = { path = "consumer_macro" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.145"

[features]
default = ["broker", "consumer"]
broker = []
consumer = []
