[package]
name = "pusu"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
rand = "0.9.2"
serde = { version = "1.0", features = ["derive"] }
broker_macro = { path = "broker_macro" }
consumer_macro = { path = "consumer_macro" }
serde_json = "1.0.145"

[features]
default = []
broker = []
consumer = []
